server:
    port: 8081
    
spring:
    datasource:
        name: open
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/open?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false
        username: root
        password: root
        filters: stat,wall,slf4j
        maxActive: 15
        initialSize: 1
        maxWait: 10000
        useUnfairLock: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        removeAbandoned: true
        removeAbandonedTimeout: 180
        logAbandoned: true
